[project]
name = "ggb"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "black>=24.10.0",
    "jupyterlab>=4.3.2",
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
    "ruff>=0.8.1",
]
