[project]
name = "ggb"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyterlab>=4.3.2",
    "openpyxl>=3.1.2",
    "pandas>=2.2.2",
    "plotly>=5.24.1",
    "taipy>=4",
    "xlrd>=2.0.1",
]
